### ISSUE TITLE
Add code coverage to CI/CD with reporting

### ISSUE THREAD

**Issue by hansl** [the-lifted-initiative/many-rs#30]
Let's aim to do this first in the many-rs repo.

**Comment by fmorency** [comment]
Rust 1.60 added support for Source-based Code Coverage. 

See 
- https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html#source-based-code-coverage
- https://doc.rust-lang.org/rustc/instrument-coverage.html

and more especially

- https://doc.rust-lang.org/rustc/instrument-coverage.html#test-coverage

**Comment by fmorency** [comment]
Fixed by #46
