### ISSUE TITLE
[Tracking] WebAuthn support

### ISSUE THREAD

**Issue by fmorency** [the-lifted-initiative/many-rs#68]
Modify MANY to support WebAuthn requests

See https://webauthn.guide/#webauthn-api

**Comment by fmorency** [comment]
The current PR #69 is a non-compliant workaround making use of the WebAuthn API.

After discussion with the team, we should work on being compliant with the WebAuthn spec.

**Comment by hansl** [comment]
ETA this week.

**Comment by fmorency** [comment]
We have a working version to demo.
